// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecapi;

namespace ecapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191123203423_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ecapi.Models.eci+Datum", b =>
                {
                    b.Property<int>("year")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("category");

                    b.Property<string>("category2");

                    b.Property<string>("category2_value");

                    b.Property<string>("category_value");

                    b.Property<int>("decimal_display");

                    b.Property<double>("estimate");

                    b.Property<string>("farmtype");

                    b.Property<double?>("median");

                    b.Property<string>("report");

                    b.Property<double>("rse");

                    b.Property<string>("state");

                    b.Property<string>("statistic");

                    b.Property<int>("unreliable_estimate");

                    b.Property<string>("variable_description");

                    b.Property<string>("variable_id");

                    b.Property<bool>("variable_is_invalid");

                    b.Property<int?>("variable_level");

                    b.Property<string>("variable_name");

                    b.Property<int>("variable_sequence");

                    b.Property<string>("variable_unit");

                    b.HasKey("year");

                    b.ToTable("Datums");
                });
#pragma warning restore 612, 618
        }
    }
}
